# Generated by Django 4.2.5 on 2023-09-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100, verbose_name='Укажите название часов')),
                ('description', models.TextField(verbose_name='Укажите описание часов')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Добавьте фото')),
                ('color', models.CharField(choices=[('Красный', 'Красный'), ('Белый', 'Белый'), ('Черный', 'Черный')], max_length=100, verbose_name='Укажите цвет')),
                ('size', models.CharField(choices=[('Большой', 'Большой'), ('Средний', 'Средний'), ('Маленький', 'Маленький')], max_length=100, verbose_name='Укажите размер')),
                ('video', models.URLField(verbose_name='Укажите ссылку')),
                ('cost', models.PositiveIntegerField(verbose_name='Укажите цену')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
