# Generated by Django 4.2.5 on 2023-09-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Каталог', 'verbose_name_plural': 'Каталоги'},
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='tittle',
            new_name='title',
        ),
        migrations.AddField(
            model_name='shop',
            name='country_made',
            field=models.TextField(max_length=50, null=True, verbose_name='Укажите страну производителя'),
        ),
    ]
