# Generated by Django 4.2.5 on 2023-09-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_shop', '0003_alter_shop_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Часы', 'verbose_name_plural': 'Часы'},
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Укажите описание часов'),
        ),
    ]
