# Generated by Django 4.2.5 on 2023-09-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_shop', '0004_alter_shop_options_alter_shop_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Добавьте фото'),
        ),
    ]
