# Generated by Django 4.2.5 on 2023-10-04 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch_shop', '0006_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Добавить отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
