# Generated by Django 4.2.5 on 2023-10-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_shop', '0008_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bank_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Напишите название банка'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='card_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Укажите номер вашей карты:'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city_live',
            field=models.IntegerField(choices=[('Бишкек', 'Бишкек'), ('Ташкент', 'Ташкент'), ('Алматы', 'Алматы'), ('Москва', 'Москва'), ('Душанбе', 'Душанбе')], null=True, verbose_name='Ваш город проживания'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country_live',
            field=models.IntegerField(choices=[(1, 'Кыргызстан'), (2, 'Казахстан'), (3, 'Россия'), (4, 'Таджикистан'), (5, 'Узбекистан')], null=True, verbose_name='Страна проживания?'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='feedback',
            field=models.IntegerField(choices=[(1, 'Все нравится'), (2, 'Не очень'), (3, 'Все прекрасно')], null=True, verbose_name='Как ваш нам сайт?'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='marriage',
            field=models.IntegerField(choices=[('Женат/замужем', 'Женат/замужем'), ('Холост(ая)', 'Холост(ая)')], null=True, verbose_name='Ваше семейное положение?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(default=15, null=True, verbose_name='Укажите возраст?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(choices=[(1, 'М'), (2, 'Ж')], null=True, verbose_name='Ваш пол'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=13, null=True, verbose_name='ваш номер сотового:'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Администратор'), (2, 'VIP Клиент'), (3, 'Клиент')], null=True, verbose_name='Выберите тип пользователя'),
        ),
    ]
