# Generated by Django 4.2.5 on 2023-10-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_shop', '0009_customuser_bank_name_customuser_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(max_length=100, null=True, verbose_name='Укажите ваш язык'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profession',
            field=models.CharField(max_length=100, null=True, verbose_name='Укажите вашу профессию'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telling_about_you',
            field=models.CharField(max_length=200, null=True, verbose_name='Расскажите не много о себе'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_hobby',
            field=models.CharField(max_length=100, null=True, verbose_name='укажите ваше хобби'),
        ),
    ]
